config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get 'about' => 'pages#about', as: :about
  get 'contact' => 'pages#contact', as: :contact

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails-Bootstrap Template</title>
  <!-- /.You can include style.css into stylesheet_link_tag too. If you do so, dont forget to add style.css in asset.rb -->
  <%= stylesheet_link_tag    'application','pages', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%=	 render 'shared/navbar' %>
<%= yield %>
    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <ul class="list-inline">
              <li>
                <a href="/">Home</a>
              </li>
              <li class="footer-menu-divider">&sdot;</li>
              <li>
                <a href="/about">About</a>
              </li>
              <li class="footer-menu-divider">&sdot;</li>
              <!--
              <li class="footer-menu-divider">&sdot;</li>
              <li>-->
                <a href="/contact">Contact</a>
              </li>
            </ul>
            <p class="copyright text-muted small">Copyright &copy; Your Company 2014. All Rights Reserved</p>
          </div>
        </div>
      </div>
    </footer>
</body>
</html>

app/views/pages/about.html.erb
<section class="banner">
  <div class="container">
    <h1>WE SOLVE DESIGN PROBLEMS</h1>
    <hr>
    <p>From the purely practical to the richly philosophical, design is the solution to a host of challenges.</p>
  </div><!-- container -->
</section><!-- section -->

<section id="about" class="page">
  <div class="container">
    <div class="content text-center">
      <div class="heading">
        <h2>Our Team.</h2>
        <div class="border"></div>
        <p>You can put any picture of your choice as Team. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat duis aute irure dolor.</p>
      </div>
      <div class="row">
        <div class="col-md-3 col-sm-6 col-xs-12 teammate animated hiding" data-animation="fadeInLeft" data-delay="600">
          <div class="profile-photo">
            <%= link_to (image_tag('1.jpg', :class=>'img-responsive'))%>
          </div>
          <div class="bio">
            <h4>John Doe</h4>
            <h5>Web Developer</h5>
            <div class="border"></div>
            <br>
            <p>You can put any picture of your choice as Team. Lorem ipsum dolor sit, consetetur sadipscing elitr, diam nonumy eirmod tempor invidunt ut labore.</p>
            <ul class="list-inline">
              <li>
                <a href="http://www.facebook.com" title="Facebook">
                  <i class="fa fa-facebook"></i>
                </a>
              </li>
              <li>
                <a href="http://www.twitter.com" title="Twitter">
                  <i class="fa fa-twitter"></i>
                </a>
              </li>
              <li>
                <a href="http://www.linkedin.com" title="LinkedIn">
                  <i class="fa fa-linkedin"></i>
                </a>
              </li>
              <li>
                <a href="http://www.github.com" title="GitHub">
                  <i class="fa fa-github"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-3 col-sm-6 col-xs-12 teammate animated hiding" data-animation="fadeInUp" data-delay="300">
          <div class="profile-photo">
            <%= link_to (image_tag('2.jpg', :class=>'img-responsive'))%>
          </div>
          <div class="bio">
            <h4>Clarinda Gratia</h4>
            <h5>Designer</h5>
            <div class="border"></div>
            <br>
            <p>You can put any picture of your choice as Team. Lorem ipsum dolor sit, consetetur sadipscing elitr, diam nonumy eirmod tempor invidunt ut labore.</p>
            <ul class="list-inline">
              <li>
                <a href="http://www.dribbble.com" title="Dribbble">
                  <i class="fa fa-dribbble"></i>
                </a>
              </li>
              <li>
                <a href="http://www.pinterest.com" title="Pinterest">
                  <i class="fa fa-pinterest"></i>
                </a>
              </li>
              <li>
                <a href="http://www.instagram.com" title="Instagram">
                  <i class="fa fa-instagram"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-3 col-sm-6 col-xs-12 teammate animated hiding" data-animation="fadeInUp" data-delay="300">
          <div class="profile-photo">
            <%= link_to (image_tag('3.jpg', :class=>'img-responsive'))%>
          </div>
          <div class="bio">
            <h4>Mandeep Eimear</h4>
            <h5>Mobile Developer</h5>
            <div class="border"></div>
            <br>
            <p>You can put any picture of your choice as Team. Lorem ipsum dolor sit, consetetur sadipscing elitr, diam nonumy eirmod tempor invidunt ut labore.</p>
            <ul class="list-inline">
              <li>
                <a href="http://www.twitter.com" title="Twitter">
                  <i class="fa fa-twitter"></i>
                </a>
              </li>
              <li>
                <a href="http://developer.android.com/index.html" title="Android Developers">
                  <i class="fa fa-android"></i>
                </a>
              </li>
              <li>
                <a href="http://www.stackoverflow.com" title="Stack Overflow">
                  <i class="fa fa-stack-overflow"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-3 col-sm-6 col-xs-12 teammate animated hiding" data-animation="fadeInRight" data-delay="600">
          <div class="profile-photo">
            <%= link_to (image_tag('4.jpg', :class=>'img-responsive'))%>
          </div>
          <div class="bio">
            <h4>Wigstan Fergus</h4>
            <h5>QA Engineer</h5>
            <div class="border"></div>
            <br>
            <p>You can put any picture of your choice as Team. Lorem ipsum dolor sit, consetetur sadipscing elitr, diam nonumy eirmod tempor invidunt ut labore.</p>
            <ul class="list-inline">
              <li>
                <a href="http://www.plus.google.com" title="Google+">
                  <i class="fa fa-google-plus"></i>
                </a>
              </li>
              <li>
                <a href="http://www.trello.com" title="Trello">
                  <i class="fa fa-trello"></i>
                </a>
              </li>
              <li>
                <a href="mailto:john.doe@mail.com" title="Email">
                  <i class="fa fa-envelope"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="twitter text-center">
    <div class="animated hiding" data-animation="fadeIn">
      <i class="fa fa-twitter fa-3x"></i>
      <div id="feed"></div>
    </div>
  </div>
</section>

app/views/pages/contact.html.erb
<!--<section>
  <div class="container">
      <div class="row">
        <li class="col-lg-3"></li>
        <li class="col-lg-8"></li>
      </div>
  </div>
</section>-->

<section id="contact" class="page">
  <div class="container">
    <div class="content cover text-center">
      <div class="heading">
        <h2>Getting in touch.</h2>
        <div class="border"></div>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
      </div>
      <div class="row">
        <div class="col-lg-4 animated hiding" data-animation="fadeInRight" data-delay="600">
          <i class="fa fa-3x"><%= link_to (image_tag('icon-home.png'))%></i>
          <a href="#">Mostar, Bosnia and Herzegovina</a>
        </div>
        <div class="col-lg-4 animated hiding" data-animation="fadeInDown" data-delay="300">
          <i class="fa fa-3x"><%= link_to (image_tag('icon-phone.png'))%></i>
          <a href="tel:9876543210">(987) 654-3210</a>
        </div>
        <div class="col-lg-4 animated hiding" data-animation="fadeInLeft" data-delay="600">
          <i class="fa fa-3x"><%= link_to (image_tag('icon-box.png'))%></i>
          <a href="mailto:john.doe@mail.com">john.doe@mail.com</a>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/pages/home.html.erb
<!--<section id="main-slider" class="no-margin">
  <div class="carousel slide">
    <ol class="carousel-indicators">
      <li data-target="#main-slider" data-slide-to="0" class="active"></li>
      <li data-target="#main-slider" data-slide-to="1"></li>
      <li data-target="#main-slider" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">

      <div class="item active" style="background-image: <%#= link_to (image_tag ('bg1.jpg'))%> ">
        <div class="container">
          <div class="row slide-margin">
            <div class="col-sm-6">
              <div class="carousel-content">
                <h1 class="animation animated-item-1">Lorem ipsum dolor sit amet consectetur adipisicing elit</h1>
                <h2 class="animation animated-item-2">Accusantium doloremque laudantium totam rem aperiam, eaque ipsa...</h2>
                <a class="btn-slide animation animated-item-3" href="#">Read More</a>
              </div>
            </div>

            <div class="col-sm-6 hidden-xs animation animated-item-4">
              <div class="slider-img">
                <img src="<%#= link_to (image_tag ('doge.png'))%> " class="img-responsive">
              </div>
            </div>

          </div>
        </div>
      </div> --><!--/.item-->

<!--<div class="item" style="background-image: url(images/banner-bg.jpg)">
  <div class="container">
    <div class="row slide-margin">
      <div class="col-sm-6">
        <div class="carousel-content">
          <h1 class="animation animated-item-1">Lorem ipsum dolor sit amet consectetur adipisicing elit</h1>
          <h2 class="animation animated-item-2">Accusantium doloremque laudantium totam rem aperiam, eaque ipsa...</h2>
          <a class="btn-slide animation animated-item-3" href="#">Read More</a>
        </div>
      </div>

      <div class="col-sm-6 hidden-xs animation animated-item-4">
        <div class="slider-img">
          <img src="images/slider/img2.png" class="img-responsive">
        </div>
      </div>

    </div>
  </div>
</div><!--/.item-->

<!--<div class="item" style="background-image: url(images/slider/bg3.jpg)">
  <div class="container">
    <div class="row slide-margin">
      <div class="col-sm-6">
        <div class="carousel-content">
          <h1 class="animation animated-item-1">Lorem ipsum dolor sit amet consectetur adipisicing elit</h1>
          <h2 class="animation animated-item-2">Accusantium doloremque laudantium totam rem aperiam, eaque ipsa...</h2>
          <a class="btn-slide animation animated-item-3" href="#">Read More</a>
        </div>
      </div>
      <div class="col-sm-6 hidden-xs animation animated-item-4">
        <div class="slider-img">
          <img src="images/slider/img3.png" class="img-responsive">
        </div>
      </div>
    </div>
  </div>
</div><!--/.item-->
<!--   </div><!--/.carousel-inner-->
<!--</div><!--/.carousel-->
<!-- <a class="prev hidden-xs" href="#main-slider" data-slide="prev">
   <i class="fa fa-chevron-left"></i>
 </a>
 <a class="next hidden-xs" href="#main-slider" data-slide="next">
   <i class="fa fa-chevron-right"></i>
 </a>
</section> <!--/#main-slider-->

<section class="intro-header">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="intro-message">
          <h1>Implementation of Ruby on Rails 4.2.5 with Twitter Bootstrap 3</h1>
          <h3>A Template by Start Bootstrap, Implemented with Ruby on Rails 4.2.5 by ~Afolabi Olaoluwa</h3>
          <hr class="intro-divider">
          <ul class="list-inline intro-social-buttons">
            <li>
              <a href="https://twitter.com/SBootstrap" class="btn btn-favorite btn-sm"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
            </li>
            <li>
              <a href="https://github.com/AfolabiOlaoluwa" class="btn btn-favorite btn-sm"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
            </li>
            <li>
              <a href="https://ng.linkedin.com/in/afolabiolaoluwa" class="btn btn-favorite btn-sm"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>  <!-- /.container -->
</section><!-- /.intro-header -->

<!-- Page Content -->

<section class="content-section-a">
  <div class="container">
    <div class="row">
      <div class="col-lg-5 col-sm-6">
        <hr class="section-heading-spacer">
        <div class="clearfix"></div>
        <h2 class="section-heading">Death to the Stock Photo:<br>Special Thanks</h2>
        <p class="lead">A special thanks to <a target="_blank" href="http://join.deathtothestockphoto.com/">Death to the Stock Photo</a> for providing the photographs that you see in this template. Visit their website to become a member.</p>
      </div>
      <div class="col-lg-5 col-lg-offset-2 col-sm-6">
        <%= link_to (image_tag('ipad.png', :size => '380x260', :class=>'img-responsive')) %>
      </div>
    </div>
  </div>  <!-- /.container -->
</section><!-- /.content-section-a -->

<div class="content-section-b">
  <div class="container">
    <div class="row">
      <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
        <hr class="section-heading-spacer">
        <div class="clearfix"></div>
        <h2 class="section-heading">3D Device Mockups<br>by PSDCovers</h2>
        <p class="lead">Turn your 2D designs into high quality, 3D product shots in seconds using free Photoshop actions by <a target="_blank" href="http://www.psdcovers.com/">PSDCovers</a>! Visit their website to download some of their awesome, free photoshop actions!</p>
      </div>
      <div class="col-lg-5 col-sm-pull-6  col-sm-6">
        <%= link_to (image_tag('doge.png', :size => '457.500x382.766', :class=>'img-responsive'))%>
      </div>
    </div>
  </div>  <!-- /.container -->
</div>
<!-- /.content-section-b -->
<!--</section>-->

<div class="content-section-a">
  <div class="container">
    <div class="row">
      <div class="col-lg-5 col-sm-6">
        <hr class="section-heading-spacer">
        <div class="clearfix"></div>
        <h2 class="section-heading">Google Web Fonts and<br>Font Awesome Icons</h2>
        <p class="lead">This template features the 'Lato' font, part of the <a target="_blank" href="http://www.google.com/fonts">Google Web Font library</a>, as well as <a target="_blank" href="http://fontawesome.io">icons from Font Awesome</a>.</p>
      </div>
      <div class="col-lg-5 col-lg-offset-2 col-sm-6">
        <%= link_to (image_tag('phones.png', :class=>'img-responsive'))%>
      </div>
    </div>
  </div>  <!-- /.container -->
</div><!-- /.content-section-a -->

<div class="banner">
  <div class="container">
    <div class="row">
      <div class="col-lg-6">
        <h2>Connect to Start Bootstrap:</h2>
      </div>
      <br>
      <div class="col-lg-6 br-space">
        <ul class="list-inline banner-social-buttons">
          <li>
            <a href="https://twitter.com/SBootstrap" class="btn btn-favorite btn-sm"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
          </li>
          <li>
            <a href="https://github.com/AfolabiOlaoluwa" class="btn btn-favorite btn-sm"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
          </li>
          <li>
            <a href="https://ng.linkedin.com/in/afolabiolaoluwa" class="btn btn-favorite btn-sm"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>
          </li>
        </ul>
      </div>
    </div>
  </div>  <!-- /.container -->
</div><!-- /.banner -->

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top topnav" role="navigation">
  <div class="container topnav">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand topnav" href="/">RoR 4.2.5 with Twbs</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%=	 link_to 'Home', root_path  %></li>
        <li> <%= link_to 'About', about_path  %></li>
        <li> <%= link_to 'Contact', contact_path  %></li>
        <!--The following li tag can be used with get 'view/view' in the routes file to navigate to pages on your site-->
        <!--<li> <%#= link_to 'Contact', pages_contact_path  %></li>-->
      </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>